#!/usr/bin/env python3
from __future__ import annotations

import sys
from pathlib import Path

REQUIRED_KEYS = ("name", "description", "version", "owner")


def strip_quotes(value: str) -> str:
    value = value.strip()
    if len(value) >= 2 and value[0] == value[-1] and value[0] in {"'", '"'}:
        return value[1:-1]
    return value


def parse_frontmatter(path: Path) -> dict[str, str]:
    text = path.read_text(encoding="utf-8")
    lines = text.splitlines()

    if not lines or lines[0].strip() != "---":
        raise ValueError("missing opening frontmatter delimiter '---'")

    end_index = None
    for idx in range(1, len(lines)):
        if lines[idx].strip() == "---":
            end_index = idx
            break
    if end_index is None:
        raise ValueError("missing closing frontmatter delimiter '---'")

    frontmatter: dict[str, str] = {}
    for raw in lines[1:end_index]:
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if ":" not in raw:
            raise ValueError(f"invalid frontmatter line: {raw!r}")
        key, value = raw.split(":", 1)
        key = key.strip()
        if not key:
            raise ValueError(f"invalid frontmatter key in line: {raw!r}")
        frontmatter[key] = strip_quotes(value)
    return frontmatter


def escape_cell(value: str) -> str:
    return value.replace("|", "\\|").strip()


def main() -> int:
    repo_root = Path(__file__).resolve().parent.parent
    skills_dir = repo_root / "skills"
    index_path = repo_root / "SKILLS_INDEX.md"

    if not skills_dir.exists() or not skills_dir.is_dir():
        print(f"Error: missing directory {skills_dir}")
        return 1

    rows: list[dict[str, str]] = []
    for skill_dir in sorted(path for path in skills_dir.iterdir() if path.is_dir()):
        skill_file = skill_dir / "SKILL.md"
        if not skill_file.exists():
            print(f"Error: missing file {skill_file}")
            return 1

        try:
            frontmatter = parse_frontmatter(skill_file)
        except Exception as exc:  # noqa: BLE001
            print(f"Error: failed to parse {skill_file}: {exc}")
            return 1

        missing = [key for key in REQUIRED_KEYS if not frontmatter.get(key)]
        if missing:
            print(f"Error: {skill_file} missing required key(s): {', '.join(missing)}")
            return 1

        rows.append(
            {
                "name": frontmatter["name"],
                "description": frontmatter["description"],
                "version": frontmatter["version"],
                "owner": frontmatter["owner"],
                "path": str(skill_file.relative_to(repo_root)),
            }
        )

    rows.sort(key=lambda item: item["name"])

    output_lines = [
        "# Skills Index",
        "",
        "> Auto-generated by `python3 scripts/reindex_skills.py`. Do not edit manually.",
        "",
        "| Name | Description | Version | Owner | Path |",
        "| --- | --- | --- | --- | --- |",
    ]

    for row in rows:
        output_lines.append(
            "| "
            + f"`{escape_cell(row['name'])}` | "
            + f"{escape_cell(row['description'])} | "
            + f"`{escape_cell(row['version'])}` | "
            + f"{escape_cell(row['owner'])} | "
            + f"`{escape_cell(row['path'])}` |"
        )

    output_lines.append("")
    index_path.write_text("\n".join(output_lines), encoding="utf-8")
    print(f"Reindexed {len(rows)} skill(s) into {index_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
